export const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS';
export const INITIAL_DATA_ERROR = 'INITIAL_DATA_ERROR';
export const INITIAL_DATA_PURGE = 'INITIAL_DATA_PURGE';

export const PDF_DATA_SUCCESS = 'PDF_DATA_SUCCESS';
export const PDF_DATA_ERROR = 'PDF_DATA_ERROR';
export const PDF_DATA_PURGE = 'PDF_DATA_PURGE';

export const FIRMA_DATA_SUCCESS = 'FIRMA_DATA_SUCCESS';
export const FIRMA_DATA_ERROR = 'FIRMA_DATA_ERROR';
export const FIRMA_DATA_PURGE = 'FIRMA_DATA_PURGE';
